Random Forest:
  n_estimators: [100, 200, 500]
  max_depth: [None, 10, 20]
  min_samples_split: [2, 5, 10]
  min_samples_leaf: [1, 2, 4]

Decision Tree:
  max_depth: [None, 10, 20, 30]
  min_samples_split: [2, 5, 10]
  min_samples_leaf: [1, 2, 4]

Gradient Boosting:
  n_estimators: [100, 200, 500]
  learning_rate: [0.01, 0.1, 0.2]
  max_depth: [3, 5, 7]
  subsample: [0.8, 1.0]

Linear Regression: {}

K - Neighbours Classifier:
  n_neighbors: [3, 5, 7, 9]
  weights: ['uniform', 'distance']
  metric: ['euclidean', 'manhattan']

XGB Classifier:
  n_estimators: [100, 200, 500]
  learning_rate: [0.01, 0.1, 0.2]
  max_depth: [3, 5, 7]
  subsample: [0.8, 1.0]
  colsample_bytree: [0.8, 1.0]

CatBoosting Classifier:
  iterations: [100, 200, 500]
  learning_rate: [0.01, 0.1, 0.2]
  depth: [3, 5, 7]

AdaBoost Classifier:
  n_estimators: [50, 100, 200]
  learning_rate: [0.01, 0.1, 1.0] 